#!/usr/bin/env sh
# shellcheck shell=dash

set -eu

_prefix="${TERMUX__PREFIX:-"${PREFIX}"}"

: "${XDG_RUNTIME_DIR:="${_prefix}/var/run"}"
export XDG_RUNTIME_DIR

BINDIR="${_prefix}/bin"
readonly BINDIR

LOGDIR="${_prefix}/var/log"
export LOGDIR
readonly LOGDIR

SVDIR="${_prefix}/var/service"
export SVDIR
readonly SVDIR

unset -v _prefix


wait_for_pid() {
    local pid="$1"
    local seconds

    for seconds in 1 2 3 4 5 ; do
        kill -0 "${pid}" 2>/dev/null || break
        sleep "${seconds}"
    done
    kill -0 "${pid}" 2>/dev/null && return 1 || return 0
}

kill_from_pid_file() {
    local pid

    for pid in $(head -n 1 "$1") ; do
        kill "${pid}"
        wait_for_pid "${pid}" || kill -9 "${pid}"
    done
}

start() {
    # shellcheck disable=SC2174
    mkdir -m 0700 -p "${XDG_RUNTIME_DIR}"
    start-stop-daemon -S -b -m -p "${PIDFILE}" -x "${DAEMON}" -d "${XDG_RUNTIME_DIR}" -- "${DAEMON_OPTS}"
}

stop() {
    local dir pid="$(cat "${PIDFILE}")"

    start-stop-daemon -K -s "${DAEMON_STOP_SIGNAL}" -o -p "${PIDFILE}"
    wait_for_pid "${pid}" || tail -f --pid="${pid}" /dev/null
    for dir in "${SVDIR}"/*/{,log/}supervise ; do
        kill_from_pid_file "${dir}/pid"
        rm -rf "${dir}"
    done
}

action_message() {
    local action_word="$1"
    shift

    printf -- '%s daemon: %s' "${action_word}" "${NAME}"
    for cmd in "$@" ; do
        "${cmd}"
    done
    printf -- '.\n'
}


# Must be a valid filename
NAME='service-daemon'
PIDFILE="${XDG_RUNTIME_DIR}/${NAME}.pid"
# This is the command to be run, give the full pathname
DAEMON="${BINDIR}/runsvdir"
DAEMON_OPTS="${SVDIR}"
# If runsvdir receives a TERM signal, it exits with 0 immediately.
# If runsvdir receives a HUP signal,
# it sends a TERM signal to each runsv(8) process it is monitoring and then exits with 111.
DAEMON_STOP_SIGNAL='HUP'


case "$1" in
    (restart)
        # this alternative looks and works like stop then start
        # action_message 'Stopping' stop
        # action_message 'Starting' start
        # call both stop and start within a single message
        action_message 'Restarting' stop start
        ;;
    (start) action_message 'Starting' "$1" ;;
    (stop) action_message 'Stopping' "$1" ;;
    (*)
        printf -- 'Usage: %s {start|stop|restart}\n' "${0##*/}"
        exit 1
        ;;
esac

exit 0
