#!/usr/bin/env sh

set -eu

_prefix="${TERMUX__PREFIX:-"${PREFIX}"}"

: "${XDG_RUNTIME_DIR:="${_prefix}/var/run"}"
export XDG_RUNTIME_DIR

BINDIR="${_prefix}/bin"
readonly BINDIR

LOGDIR="${_prefix}/var/log"
export LOGDIR
readonly LOGDIR

SVDIR="${_prefix}/var/service"
export SVDIR
readonly SVDIR

unset -v _prefix


wait_for_pid() (
    local pid="$1"
    local s

    for s in 1 2 3 4 5
    do
        kill -0 "${pid}" 2>/dev/null || break
        sleep "$s"
    done
    kill -0 "${pid}" 2>/dev/null && return 1 || return 0
}

kill_from_pid_file() {
    local pid

    for pid in $(head -n 1 "$1")
    do
        kill "${pid}"
        wait_for_pid "${pid}" || kill -9 "${pid}"
    done
}

start() {
    mkdir -m 00700 -p "${XDG_RUNTIME_DIR}"
    start-stop-daemon -S -b -m -p "${PIDFILE}" -x "${DAEMON}" -d "${XDG_RUNTIME_DIR}" -- "${DAEMON_OPTS}"
}

stop() {
    local d pid="$(cat "${PIDFILE}")"

    start-stop-daemon -K -s "${DAEMON_STOP_SIGNAL}" -o -p "${PIDFILE}"
    wait_for_pid "${pid}" || tail -f --pid="${pid}" /dev/null
    for d in "${SVDIR}"/*/supervise "${SVDIR}"/*/log/supervise
    do
        kill_from_pid_file "${d}/pid"
        rm -rf "${d}"
    done
}


# Must be a valid filename
NAME='service-daemon'
PIDFILE="${XDG_RUNTIME_DIR}/${NAME}.pid"
# This is the command to be run, give the full pathname
DAEMON="${BINDIR}/runsvdir"
DAEMON_OPTS="${SVDIR}"
# If runsvdir receives a TERM signal, it exits with 0 immediately.
# If runsvdir receives a HUP signal,
# it sends a TERM signal to each runsv(8) process it is monitoring and then exits with 111.
DAEMON_STOP_SIGNAL='HUP'


case "$1" in
    (restart) printf -- 'Restart' ;;
    (start) printf -- 'Start' ;;
    (stop) printf -- 'Stopp' ;;
esac
case "$1" in
    (restart|start|stop)
        printf -- 'ing daemon: %s' "${NAME}"
        ;;
esac
case "$1" in
    (start|stop) "$1" ;;
    (restart)
        stop
        start
        ;;
    *)
        printf -- 'Usage: %s {start|stop|restart}\n' "${0##*/}"
        exit 1
esac
printf -- '.\n'

exit 0
