#!/usr/bin/env sh

show_help(){
    printf -- 'Usage:
    sv-disable <service-name>

    Disabling a service will make it not autostart
'
}

if [ -z "$1" ];then
    show_help
    exit 1
fi
if [ -z "${SVDIR}" ];then
    1>&2 echo "Error: SVDIR not set"
    exit 1
fi

: >> "${SVDIR}/${1}/down"
sv down "$1"
