#!/usr/bin/env sh
# shellcheck shell=dash

default_vars() {
    local prefix="${TERMUX__PREFIX:-"${PREFIX}"}"

    : "${LOGDIR:="${prefix}/var/log"}"
    export LOGDIR

    : "${SVDIR:="${prefix}/var/service"}"
    export SVDIR
}

show_help() {
    printf -- 'Usage:
    sv-disable <service-name>

    Disabling a service will make it not autostart
'
}

if [ -z "$1" ];then
    show_help
    exit 1
fi

touch_in_sh() {
    local file
    for file in "$@" ; do
        : >> "${file}"
    done
}

default_vars
touch_in_sh "${SVDIR}/${1}/down"
sv down "$1"
