#!/usr/bin/env sh
# shellcheck shell=dash

default_vars() {
    local prefix="${TERMUX__PREFIX:-"${PREFIX}"}"

    : "${LOGDIR:="${prefix}/var/log"}"
    export LOGDIR

    : "${SVDIR:="${prefix}/var/service"}"
    export SVDIR
}

show_help() {
    printf -- 'Usage:
    sv-enable <service-name>

    Enabling a service will make it autostart
'
}

if [ -z "$1" ];then
    show_help
    exit 1
fi

default_vars
rm -f "${SVDIR}/${1}/down"
sv up "$1"
